CREATE TABLE users (

    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	user_spec_id UUID,

    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
	role VARCHAR(255) DEFAULT 'CLIENT',
	active BOOLEAN DEFAULT TRUE,

	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);